### ISSUE TITLE
Train config is not compatible with analyze.

### ISSUE THREAD

**Issue by zurk** [src-d/lookout-sdk-ml#17]
We have two kinds of config in `FormatAnalyzer`. One is for `train` and another one is for `analyze`. They are completely different. There is one situation when `lookout-sdk-ml` tries to feed analyze config to train: if there is no model was found in the database and you should train it first:

here is related part of `process_review_event()` function: 
https://github.com/src-d/lookout-sdk-ml/blob/641bf7ec0baa72501bf1e53b0b356d5f14acce61/lookout/core/manager.py#L73-L76

so in line # 75 we feed config for review as train config.

So we have 4 ways for a solution here:
1. Do not train model during analyze phase at all. So in 
2. Explicitly reqire to have 2 different configs for review event. 
3. Include train config into analyzing config. So we get next structure: 
```
analyze_config = {
    "train_config" : {...}
    "confidence_threshold": 0.95,
    "support_threshold": 80,
    "report_code_lines": True,
}
```
4. Harmonize configs for `push` and `review` event. Have union structure for both configs:
```
analyze_config = {
    "train_config" : {...}
    "analyze_config": {...}
}
```

cc @vmarkovtsev

**Comment by vmarkovtsev** [comment]
So Lookout does not know anything about stateful analyzers, and hence the `config` object is by design the same for training and analyzing. Each analyzer has to work around it individually. Once we see some pattern, we can revise this issue and elaborate a standard solution.
