### ISSUE TITLE
Do not fail on repository if grpc error happens on one file. 

### ISSUE THREAD

**Issue by zurk** [src-d/lookout-sdk-ml#24]
There is an issue with bblfsh python client related to grpc: https://github.com/bblfsh/client-python/issues/89
We hit it once https://github.com/src-d/lookout/issues/404 and fix it: https://github.com/src-d/lookout-sdk-ml/pull/20

However, right now we fail to process all repo because of grpc error on one file. 
So this issue is a suggestion to fail only on one file and not on all repo if we get a grpc error

Repositories that are affected by this issue with commits:
https://github.com/vuejs/vue b7105ae8c9093e36ec89a470caa3b78bda3ef467 
https://github.com/vuejs/vuex 2e62705d4bce4ebcb8eca23df8c7b849125fc565

**Comment by vmarkovtsev** [comment]
Such a grpc error poisons the whole session, also the name of the offending file is obviously not reported. Finally, the problem no longer exists in the new protocol version. Closing as WONTFIX because we are going to port to the new protocol.
