### ISSUE TITLE
Use src-d/ci to push versioned docker images

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/lookout-sdk-ml#69]
Although DockerHub says that it supports tagging images, and even has the corresponding UI settings, it doesn't in practice because of throttling concurrent builds. We need to leverage `src-d/ci` as we already do in style-analyzer and push tagged images automatically.

**Comment by vmarkovtsev** [comment]
Re-assigning this to @Guillemdb

**Comment by vmarkovtsev** [comment]
@Guillemdb ping here

**Comment by Guillemdb** [comment]
I have it ready locally, I will make the PR once the last one I made its merged. When I do PR on top of PR I end up spending more time rebasing than actually writing code :P

**Comment by vmarkovtsev** [comment]
Done
